services:
    backend:
        build:
            context: .
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=app_user
            - DB_PASSWORD=app_password
            - DB_NAME=testdb

    db:
        image: postgres:13
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: app_user
            POSTGRES_PASSWORD: app_password
            POSTGRES_DB: testdb
        ports:
            - "5432:5432"

volumes:
    pgdata:
